# WARNING! Do not place any sensative infomration in this file (e.g. Postgres passwords).
# The image repo on Dockerhub for this is public. If you absolutely have to, then make
# the repo private.
FROM postgres:10.5

RUN apt-get update
RUN apt-get install -y postgis postgresql-10-postgis-2.4
